const dataset = [
    { "message": "Hey, are we still on for dinner tonight?", "label": 0 },
    { "message": "Don't forget to submit your assignment by Friday.", "label": 0 },
    { "message": "Happy Birthday! Hope you have a great day!", "label": 0 },
    { "message": "Can you send me the report by tomorrow?", "label": 0 },
    { "message": "Let's catch up for coffee this weekend.", "label": 0 },
    { "message": "I will be out of the office next week.", "label": 0 },
    { "message": "Did you see the new movie that just came out?", "label": 0 },
    { "message": "Please find the attached files for your review.", "label": 0 },
    { "message": "Great job on the presentation today!", "label": 0 },
    { "message": "The meeting has been rescheduled to 2 PM.", "label": 0 },
    { "message": "Let me know if you need any help with the project.", "label": 0 },
    { "message": "I’ll be arriving around 3 PM. See you then!", "label": 0 },
    { "message": "Congratulations on your promotion!", "label": 0 },
    { "message": "Can you please confirm your attendance for the event?", "label": 0 },
    { "message": "Looking forward to our trip next month!", "label": 0 },
    { "message": "I'll send over the documents later today.", "label": 0 },
    { "message": "Is the meeting still happening tomorrow morning?", "label": 0 },
    { "message": "I hope you’re doing well. Long time no see!", "label": 0 },
    { "message": "Please remember to clock in before 9 AM.", "label": 0 },
    { "message": "Can we move our lunch meeting to Thursday?", "label": 0 },
    { "message": "The package should arrive by the end of the week.", "label": 0 },
    { "message": "How was your weekend? Did you go anywhere fun?", "label": 0 },
    { "message": "Just wanted to check in and see how you're doing.", "label": 0 },
    { "message": "I’ll be working from home today. Let me know if you need anything.", "label": 0 },
    { "message": "Can you send me the login details for the meeting?", "label": 0 },
    { "message": "We should plan a trip sometime soon!", "label": 0 },
    { "message": "Thanks for your help with the project last week.", "label": 0 },
    { "message": "Are you available for a quick call this afternoon?", "label": 0 },
    { "message": "I’ll email you the proposal by the end of the day.", "label": 0 },
    { "message": "Don't forget we have a team meeting at 11 AM.", "label": 0 },
    { "message": "Looking forward to seeing you at the event tomorrow!", "label": 0 },
    { "message": "Can you send me the updated document by this evening?", "label": 0 },
    { "message": "Just wanted to remind you about the deadline.", "label": 0 },
    { "message": "Let me know when you’re free to meet up.", "label": 0 },
    { "message": "Thank you for your feedback on the report.", "label": 0 },
    { "message": "I will review the contract and get back to you.", "label": 0 },
    { "message": "Can you help me with the setup for tomorrow’s meeting?", "label": 0 },
    { "message": "The conference was really informative. You should attend next year.", "label": 0 },
    { "message": "Let me know if you’re free for lunch tomorrow.", "label": 0 },
    { "message": "The weather is great today. Let's go for a walk later.", "label": 0 },
    { "message": "I’ll send you the final draft later this week.", "label": 0 },
    { "message": "Great job on completing the project ahead of time!", "label": 0 },
    { "message": "I’ll check in with you later to see how everything is going.", "label": 0 },
    { "message": "I hope you’re doing well. Let’s catch up soon.", "label": 0 },
    { "message": "I need your feedback on the proposal before Friday.", "label": 0 },
    { "message": "Thanks for your help earlier today!", "label": 0 },
    { "message": "Let me know if you're free to discuss the project.", "label": 0 },
    { "message": "Are you attending the conference next week?", "label": 0 },
    { "message": "I will review the document and provide my comments by tomorrow.", "label": 0 },
    { "message": "Please let me know if the meeting time works for you.", "label": 0 },
    { "message": "I’ll give you a call later this afternoon.", "label": 0 },
    { "message": "Do you want to grab lunch later this week?", "label": 0 },
    { "message": "I have attached the report you requested.", "label": 0 },
    { "message": "Looking forward to working together on this project!", "label": 0 },
    { "message": "Did you get a chance to review the documents?", "label": 0 },
    { "message": "Let me know if you need any help with the report.", "label": 0 },
    { "message": "I’ll send over the latest updates by end of day.", "label": 0 },
    { "message": "Can we reschedule the meeting to next week?", "label": 0 },
    { "message": "Do you have time for a quick call this afternoon?", "label": 0 },
    { "message": "I’ll bring the documents with me to the meeting.", "label": 0 },
    { "message": "Great to hear from you! Let’s catch up soon.", "label": 0 },
    { "message": "Thanks for your help with the presentation!", "label": 0 },
    { "message": "I’ll get back to you once I’ve reviewed the document.", "label": 0 },
    { "message": "Can you confirm the meeting time for tomorrow?", "label": 0 },
    { "message": "Are we still on for the meeting at 10 AM?", "label": 0 },
    { "message": "I'll send the updated version once it's ready.", "label": 0 },
    { "message": "Please let me know if you have any questions.", "label": 0 },
    { "message": "I’ll send you the final version of the document tomorrow.", "label": 0 },
    { "message": "Let’s touch base later this week.", "label": 0 },
    { "message": "Thanks again for your help with the project.", "label": 0 },
    { "message": "I'll follow up with you next week regarding the contract.", "label": 0 },
    { "message": "Are you free for a meeting later this afternoon?", "label": 0 },
    { "message": "I hope you're having a great day!", "label": 0 },
    { "message": "I’ll send you the updated files by tomorrow.", "label": 0 },
    { "message": "Can we meet up tomorrow to discuss the project?", "label": 0 },
    { "message": "I’ll email you the agenda for the meeting later today.", "label": 0 },
    { "message": "Thank you for your quick response!", "label": 0 },
    { "message": "Please review the attached documents before the meeting.", "label": 0 },
    { "message": "Looking forward to our meeting tomorrow.", "label": 0 },
    { "message": "I’ll send over the invoice later today.", "label": 0 },
    { "message": "Let me know if you need anything else before the meeting.", "label": 0 },
    { "message": "Thanks for letting me know. I’ll see you tomorrow.", "label": 0 },
    { "message": "Can you please confirm if you received the documents?", "label": 0 },
    { "message": "Win a brand-new iPhone! Click here now!", "label": 1 },
    { "message": "Congratulations! You’ve won $1000. Claim your prize!", "label": 1 },
    { "message": "Urgent! Your account has been suspended. Verify now.", "label": 1 },
    { "message": "Get rich overnight with this one simple trick!", "label": 1 },
    { "message": "You have an unclaimed gift card waiting for you!", "label": 1 },
    { "message": "Exclusive deal! Limited time offer on luxury watches!", "label": 1 },
    { "message": "You’ve been selected for a free vacation! Book now!", "label": 1 },
    { "message": "Don’t miss out! Lowest mortgage rates available.", "label": 1 },
    { "message": "Immediate action required! Your computer is infected.", "label": 1 },
    { "message": "Unlock your account now before it’s too late.", "label": 1 },
    { "message": "Earn $500 a day working from home! Sign up today.", "label": 1 },
    { "message": "Your payment couldn’t be processed. Update info here.", "label": 1 },
    { "message": "Click here to learn the secret of weight loss!", "label": 1 },
    { "message": "Claim your $50 Amazon gift card today!", "label": 1 },
    { "message": "New crypto alert! Invest now and double your earnings.", "label": 1 },
    { "message": "Special discount! Get 90% off on all purchases!", "label": 1 },
    { "message": "Confirm your account details now for security reasons.", "label": 1 },
    { "message": "Free access to exclusive adult content! Click now.", "label": 1 },
    { "message": "Immediate attention needed: Your bank account is at risk.", "label": 1 },
    { "message": "Your parcel is waiting! Pay now to release it.", "label": 1 },
    { "message": "You have been pre-approved for a $10,000 loan.", "label": 1 },
    { "message": "Click here to upgrade your antivirus software.", "label": 1 },
    { "message": "Hurry! Your gift card is about to expire.", "label": 1 },
    { "message": "Get an all-expenses-paid trip to Hawaii! Apply now.", "label": 1 },
    { "message": "Limited time only! Get your free samples today.", "label": 1 },
    { "message": "Click now to secure your exclusive VIP membership.", "label": 1 },
    { "message": "Last chance to secure your spot for a free webinar.", "label": 1 },
    { "message": "Your account has been hacked. Click to restore access.", "label": 1 },
    { "message": "Congratulations! You’ve been chosen for a special reward.", "label": 1 },
    { "message": "Open this message to claim your exclusive offer.", "label": 1 },
    { "message": "Free trial of the best weight loss product ever.", "label": 1 },
    { "message": "You’ve won a lottery! Claim your winnings now.", "label": 1 },
    { "message": "Act now! Limited spots available for free entry.", "label": 1 },
    { "message": "Your subscription is about to expire. Renew now.", "label": 1 },
    { "message": "Confirm your password to avoid account deactivation.", "label": 1 },
    { "message": "Exclusive opportunity to earn passive income. Join now!", "label": 1 },
    { "message": "Urgent! Your Apple ID is expiring. Confirm details.", "label": 1 },
    { "message": "Your PayPal account needs immediate verification.", "label": 1 },
    { "message": "You’ve been selected for a free car giveaway!", "label": 1 },
    { "message": "Click here to claim your $100 shopping voucher.", "label": 1 },
    { "message": "Unlock your dream job by clicking this link!", "label": 1 },
    { "message": "Free consultation with top financial advisors.", "label": 1 },
    { "message": "Verify your identity to avoid account closure.", "label": 1 },
    { "message": "Download this app and get exclusive rewards.", "label": 1 },
    { "message": "You’ve won a free stay at a luxury hotel!", "label": 1 },
    { "message": "One-click to reset your password instantly.", "label": 1 },
    { "message": "Your invoice is ready. Download now.", "label": 1 },
    { "message": "Final notice: Pay now to avoid legal action.", "label": 1 },
    { "message": "Free gift cards for the first 100 signups!", "label": 1 },
    { "message": "Click here to secure your spot for a free seminar.", "label": 1 },
    { "message": "Your PayPal account has been compromised. Act now.", "label": 1 },
    { "message": "Unbelievable! Double your investment with this method.", "label": 1 },
    { "message": "Free Bitcoins waiting for you! Claim them now.", "label": 1 },
    { "message": "Your credit score has been boosted. View now.", "label": 1 },
    { "message": "Urgent security update required for your device.", "label": 1 },
    { "message": "You’ve been selected for a free shopping spree!", "label": 1 },
    { "message": "Click now to reveal the secret to financial success.", "label": 1 },
    { "message": "Your order has been shipped. Track it here.", "label": 1 },
    { "message": "Join now to receive your exclusive VIP rewards.", "label": 1 },
    { "message": "Receive 50% cashback on all purchases today only.", "label": 1 },
    { "message": "You’re eligible for a free medical consultation.", "label": 1 },
    { "message": "Activate your free trial membership now.", "label": 1 },
    { "message": "Your flight booking is confirmed. Check details here.", "label": 1 },
    { "message": "Unlock instant access to premium content.", "label": 1 },
    { "message": "Your card has been charged. View the transaction here.", "label": 1 },
    { "message": "Final reminder: Confirm your shipping address.", "label": 1 },
    { "message": "Click to resolve your pending payment issue.", "label": 1 },
    { "message": "Your refund is available. Click to claim it.", "label": 1 },
    { "message": "Congratulations! You’ve won a $500 Walmart gift card.", "label": 1 },
    { "message": "Access your free trial of premium services now.", "label": 1 },
    { "message": "Special offer: Buy one, get one free!", "label": 1 },
    { "message": "Verify your email for a chance to win big!", "label": 1 },
    { "message": "Click now for an instant loan approval.", "label": 1 },
    { "message": "Claim your free health supplement samples today.", "label": 1 },
    { "message": "Your account is flagged for suspicious activity.", "label": 1 },
    { "message": "Unlock your exclusive Black Friday deals here.", "label": 1 },
    { "message": "Hurry! Your limited-time offer is about to expire.", "label": 1 },
    { "message": "Claim your bonus reward points before they expire.", "label": 1 },
    { "message": "Final call to redeem your cash prize.", "label": 1 },
    { "message": "Your purchase is pending. Confirm now.", "label": 1 },
    { "message": "Click here to view your mobile bill statement.", "label": 1 },
    { "message": "Last chance! Act now to secure your prize.", "label": 1 },
    { "message": "Your credit card details need to be updated.", "label": 1 },
    { "message": "Congratulations! You’ve won free groceries for a year.", "label": 1 },
    { "message": "Claim your free entry to the sweepstakes.", "label": 1 },
    { "message": "Activate your loyalty points before they expire.", "label": 1 },
    { "message": "Download this app for exclusive cashback offers.", "label": 1 },
    { "message": "Your order is waiting for confirmation. Click here.", "label": 1 },
]
  